# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "tickly"
  s.version = "2.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Julik Tarkhanov"]
  s.date = "2013-03-23"
  s.description = "Parses the subset of the TCL grammar needed for Nuke scripts"
  s.email = "me@julik.nl"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "lib/tickly.rb",
    "lib/tickly/curve.rb",
    "lib/tickly/evaluator.rb",
    "lib/tickly/node_processor.rb",
    "lib/tickly/parser.rb",
    "test/helper.rb",
    "test/test-data/huge_nuke_tcl.tcl",
    "test/test-data/nuke7_tracker_2tracks.nk",
    "test/test-data/nuke_group.txt",
    "test/test-data/nukenode.txt",
    "test/test-data/one_node_with_one_param.txt",
    "test/test-data/one_tracker_with_break.nk",
    "test/test-data/one_tracker_with_break_in_grp.nk",
    "test/test-data/three_nodes_and_roto.txt",
    "test/test-data/tracker_with_differing_gaps.nk",
    "test/test-data/tracker_with_repeating_gaps.nk",
    "test/test_curve.rb",
    "test/test_evaluator.rb",
    "test/test_node_processor.rb",
    "test/test_parser.rb",
    "tickly.gemspec"
  ]
  s.homepage = "http://github.com/julik/tickly"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Assists in parsing Nuke scripts in TCL"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bychar>, ["~> 2"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<ruby-prof>, [">= 0"])
    else
      s.add_dependency(%q<bychar>, ["~> 2"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<ruby-prof>, [">= 0"])
    end
  else
    s.add_dependency(%q<bychar>, ["~> 2"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<ruby-prof>, [">= 0"])
  end
end

